version: "3.8"

services:
  worker:
    image: soar009/node-service-image:v5
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
        max_replicas_per_node: 1  # 确保每个 Worker 只能运行 1 个副本
      resources:
        limits:
          cpus: "0.8"
    ports:
      - "8080:8080"
    environment:
      - WORKER_ID={{.Node.Hostname}}  # 让 Swarm 读取 Worker ID
    networks:
      - node-service-net

networks:
  node-service-net:
    driver: overlay
